# Generated by Django 2.2.7 on 2019-12-21 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentgroup',
            name='assessment_type',
            field=models.CharField(choices=[('qa', 'Quality Assurance'), ('qc', 'Quality Control')], default='qc', max_length=16, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='assessor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessment_group_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessed by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='assessment_type',
            field=models.CharField(choices=[('qa', 'Quality Assurance'), ('qc', 'Quality Control')], max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessment_set', to=settings.AUTH_USER_MODEL, verbose_name='Assessed by'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete')], default='draft', max_length=16, verbose_name='Status'),
        ),
    ]
